// Generated by CoffeeScript 1.6.3
(function() {
  (function($) {
    var App;
    App = {
      init: function() {
        this.cacheElement();
        this.bindEvents();
      },
      cacheElement: function() {
        this.foo = $('#foo');
      },
      bindEvents: function() {
        this.foo.click(this.clickMe);
      },
      clickMe: function(event) {
        event.preventDefault();
        alert("Click me!");
      }
    };
    App.init();
  })(jQuery);

}).call(this);
